compressionLevel: 0

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs

changesetBaseRefs:
  - "HEAD~1"

changesetIgnorePatterns:
  - ".yarnrc.yml"
  - ".github"
  - ".yarn"

nmHoistingLimits: workspaces

defaultSemverRangePrefix: ""
