name: Publish

on:
  workflow_run:
    workflows:
      - 'Version'
    types:
      - completed
  workflow_dispatch:

jobs:
  run:
    name: Publish
    uses: rees46/workflow/.github/workflows/reusable-publish.yaml@master
    permissions: write-all
    secrets:
      npmAuthToken: ${{ secrets.NPM_TOKEN }}
    if: contains(github.event.head_commit.message, 'versions')
