name: Version, publish and release

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Start JS action
        uses: rees46/workflow/.github/actions/js/start-js@master
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}

      - name: Find base commit
        id: base_commit
        uses: rees46/workflow/.github/actions/js/find-base-commit-js@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        if: ${{ !contains(github.event.pull_request.title, 'Revert') || !contains(github.event.pull_request.title, 'revert') }}
        uses: rees46/workflow/.github/actions/js/version-js@master
        with:
          checkChanges: 'true'
          private: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          exclude: '{.,sdkdev}'

      - name: Create changelog and publish
        if: ${{ !contains(github.event.pull_request.title, 'Revert') || !contains(github.event.pull_request.title, 'revert') }}
        uses: rees46/workflow/.github/actions/js/changelog-and-publish-js@master
        with:
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          npmAuthToken: ${{ secrets.NPM_TOKEN }}
          onlyChangelog: 'false'
          exclude: '{.,sdkdev}'

      - name: Commit changes
        if: ${{ !contains(github.event.pull_request.title, 'Revert') || !contains(github.event.pull_request.title, 'revert') }}
        uses: rees46/workflow/.github/actions/js/commit-js@master
        with:
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '{.,sdkdev}'

      - name: Create release
        if: ${{ !contains(github.event.pull_request.title, 'Revert') || !contains(github.event.pull_request.title, 'revert') }}
        uses: rees46/workflow/.github/actions/js/release-js@master
        with:
          isMonorepo: 'true'
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '{.,sdkdev}'

      - name: Delete release
        if: ${{ contains(github.event.pull_request.title, 'Revert') || contains(github.event.pull_request.title, 'revert') }}
        uses: rees46/workflow/.github/actions/js/delete-release-js@master
        with:
          isMonorepo: 'true'
          baseCommit: ${{ steps.base_commit.outputs.baseCommit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '{.,sdkdev}'
