name: Reusable publish

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 18.19 as it is in action cache'
        default: '18.19'
        required: false
        type: string
    secrets:
      npmAuthToken:
        required: true

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: yarn install

      - name: Npm Publish
        run: |
          yarn version apply --all
          yarn workspaces foreach --since --verbose --topological --no-private npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.npmAuthToken }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default_author: github_actions
          author_email: github-bot@atls.team
          message: 'chore(common): publish'
          add: '["*.lock", "*.json", "*.yml"]'
