name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - '**.js*'
      - '**.ts*'
      - '**.css'
      - '**.scss'
      - 'package.json'
      - '**.md'
      - '**.html'
      - '**rc'
      - '**.vue'

jobs:
  run:
    name: Version
    uses: rees46/workflow/.github/workflows/reusable-version.yaml@master
    permissions: write-all
