name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  run:
    name: Version
    uses: ./.github/workflows/reusable-version.yaml
    if: github.event.pull_request.merged == true
